name: Build and deploy Jekyll Webpack Blog

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.4.0
 
      - name: Install and Build 
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install zlib1g-dev
          node -v
          npm -v
          echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
          echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
          echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          sudo gem install sass compass jekyll bundler:1.16.4
          npm install
          bundler install
          npm run build        

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}
