### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Haade.fr
email: administrateur@haade.fr
description: Home assistance Alsace domotique et electronique
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#c0ffee'
twitter_username: nicoxygen
github_username:  nicoxygen
author: Nicolas Rodriguez
logo: assets/images/icon.webp
twitter:
  username: nicoxygen
social:
  name: Nicolas Rodriguez
  links:
    - https://twitter.com/sandochee
    - https://www.facebook.com/sandoche
    - https://www.linkedin.com/in/sandoche
    - https://plus.google.com/+SandocheADITTANE
    - https://github.com/sandoche

languages: ["en"]
ampdir: amp
netlify_cms: false

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

cookie_consent: false

### Build settings
markdown: kramdown
minify_html: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll
  - jekyll-toc
  - jekyll-paginate
  - jekyll-figure
  - jekyll-archives
  - jekyll-gist

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
